#!/usr/bin/env python3
"""Shared helpers for paper-hardening result generation."""

from __future__ import annotations

import csv
import datetime as dt
import json
import subprocess
from pathlib import Path
from typing import Iterable


REPO_ROOT = Path(__file__).resolve().parent.parent
RESULTS_DIR = REPO_ROOT / "results"
PAPER_TABLES_DIR = REPO_ROOT / "paper" / "tables"
PAPER_FIGURES_DIR = REPO_ROOT / "paper" / "figures"


def ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def git_commit() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short=8", "HEAD"],
            cwd=str(REPO_ROOT),
            text=True,
        ).strip()
    except Exception:
        return "unknown"


def load_json(path: Path):
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def write_json(path: Path, payload) -> None:
    ensure_parent(path)
    with path.open("w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2)
        fh.write("\n")


def write_csv(path: Path, rows: list[dict], fieldnames: Iterable[str]) -> None:
    ensure_parent(path)
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(fieldnames))
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def write_text(path: Path, text: str) -> None:
    ensure_parent(path)
    path.write_text(text, encoding="utf-8")


def latex_cell(value) -> str:
    if value is None:
        return "TODO"
    if isinstance(value, float):
        return f"{value:.3f}".rstrip("0").rstrip(".")
    return str(value)


def make_tex_table(
    caption: str,
    label: str,
    headers: list[str],
    rows: list[list[object]],
    note: str,
    colfmt: str,
) -> str:
    lines = [
        "% Auto-generated by paper-hardening script",
        "\\begin{table}[t]",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        f"\\begin{{tabular}}{{{colfmt}}}",
        "\\toprule",
        " & ".join(headers) + " \\\\",
        "\\midrule",
    ]
    for row in rows:
        lines.append(" & ".join(latex_cell(v) for v in row) + " \\\\")
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            f"\\par\\vspace{{2pt}}\\raggedright\\footnotesize\\textit{{{note}}}",
            "\\end{table}",
            "",
        ]
    )
    return "\n".join(lines)
